apiVersion: skaffold/v1
kind: Config
metadata:
  name: skupper-messaging-demo
build:
  artifacts:
    - image: quay.io/rhdevelopers/skupper-messaging-demo
deploy:
  kubectl:
    manifests:
      - k8s/app.yaml
